# Generated by Django 4.0.6 on 2022-07-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokedex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokename", models.CharField(max_length=255)),
                ("health_point", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Electric", "Electric"),
                            ("Fighting", "Fighting"),
                            ("Fire", "Fire"),
                            ("Grass", "Grass"),
                            ("Ground", "Ground"),
                            ("Normal", "Normal"),
                            ("Psychic", "Psychic"),
                            ("Water", "Water"),
                            ("Rock", "Rock"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
