# Generated by Django 4.1rc1 on 2022-07-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0003_seed_pokedex"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.IntegerField()),
                (
                    "tried",
                    models.IntegerField(
                        choices=[(0, "Not Yet"), (1, "Once"), (2, "Twice")], default=0
                    ),
                ),
                ("trainer", models.CharField(max_length=255)),
            ],
        ),
    ]
