# Generated by Django 4.1rc1 on 2022-07-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0004_guessgame"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trainer", models.CharField(max_length=255)),
                ("pokedex_id", models.IntegerField()),
            ],
        ),
    ]
