# Generated by Django 4.1rc1 on 2022-07-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0008_alter_pokemon_pokedex_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="guessgame",
            name="prize",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon.pokemon",
            ),
        ),
    ]
