# Generated by Django 4.1rc1 on 2022-07-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0009_guessgame_prize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guessgame",
            name="prize",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pokemon.pokemon"
            ),
        ),
    ]
