# Generated by Django 4.1rc1 on 2022-07-27 16:34

from django.db import migrations


_user = {"username": "user", "password": "12345"}


def unseed_users(apps, _):
    User = apps.get_model("auth", "User")
    user = User.get(username=_user["username"])
    user.delete()


def seed_users(apps, _):
    User = apps.get_model("auth", "User")
    user = User.objects.create_user(_user["username"], password=_user["password"])
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0012_rename_pokedex_id_pokemon_pokedex"),
    ]

    operations = [
        migrations.RunPython(seed_users, unseed_users),
    ]
